env:
  global:
  - SWIFT_BRANCH=swift-5.0.1-release
  - SWIFT_VERSION=swift-5.0.1-RELEASE
language: swift
osx_image: xcode10.2
sudo: required
install:
- wget https://swift.org/builds/$SWIFT_BRANCH/xcode/$SWIFT_VERSION/$SWIFT_VERSION-osx.pkg
- sudo installer -pkg $SWIFT_VERSION-osx.pkg -target /
- export PATH="/Library/Developer/Toolchains/$SWIFT_VERSION.xctoolchain/usr/bin:$PATH"
script:
- swift package update
- swift build
